/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saúde da API e DT_GERACAO dos dados
         * @description 200 quando os dados abrem; 503 caso contrário.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dimensões disponíveis para filtros
         * @description Anos, UFs e cargos presentes nos dados + grupos configurados.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Grupo
         * @description Grupo comparável definido em config/grupos.yaml.
         */
        Grupo: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** Ano */
            ano: number;
        };
        /**
         * Meta
         * @description Dimensões disponíveis para filtros.
         */
        Meta: {
            /** Anos */
            anos: number[];
            /** Ufs */
            ufs: string[];
            /** Cargos */
            cargos: string[];
            /** Grupos */
            grupos: components["schemas"]["Grupo"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * Saude
         * @description Estado da API e dos dados.
         */
        Saude: {
            /** Status */
            status: string;
            /** Versao */
            versao: string;
            /** Dt Geracao */
            dt_geracao: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
}
