/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saúde da API e DT_GERACAO dos dados
         * @description 200 quando os dados abrem; 503 caso contrário.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dimensões disponíveis para filtros
         * @description Anos, UFs e cargos presentes nos dados + grupos configurados.
         */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grupos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Grupos e comparações
         * @description Grupos configurados (com nº de candidaturas nos dados) e comparações entre eles.
         */
        get: operations["grupos_api_grupos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidatos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidatos de um grupo
         * @description Votos, % dos válidos, penetração, resultado e partido, ordenados por votos.
         */
        get: operations["candidatos_api_candidatos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidatos/{ano}/{sq_candidato}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha do candidato
         * @description Votos por UF e município (top N), gastos, receitas por fonte e custo por voto.
         */
        get: operations["ficha_api_candidatos__ano___sq_candidato__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mapa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicador por território
         * @description `valores` por território (município, `município-zona` ou célula H3) + escala sugerida.
         */
        get: operations["mapa_api_mapa_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mapa/pontos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Locais de votação (densidade)
         * @description `{lat, lon, votos}` por local, mais votados primeiro; paginado.
         */
        get: operations["pontos_api_mapa_pontos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gastos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gastos e receitas do grupo
         * @description Custo por voto (contratado/pago), receita por fonte, % público e % autofinanciamento.
         */
        get: operations["gastos_api_gastos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparativo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evolução 2022→2026
         * @description Δ penetração (‰), swing (p.p.), retenção e ganho por AMC, mais KPIs do recorte.
         *
         *     Dois modos: `comparacao` (grupos configurados) ou uma seleção (`pessoas`, `sq_2022`,
         *     `sq_2026`). Sem candidaturas dos dois lados no cargo/UF → 422 `sem_par_comparavel`.
         */
        get: operations["comparativo_api_comparativo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/busca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca de candidaturas
         * @description Candidaturas com ano, cargo, UF, partido, votos, resultado e `abrangencia` do mapa.
         */
        get: operations["busca_api_busca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evolucao/pessoas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pessoas em 2022 e 2026
         * @description Quem concorreu nos dois anos, com o resumo de cada ano; alimenta `/comparativo?pessoas=`.
         */
        get: operations["evolucao_pessoas_api_evolucao_pessoas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/municipios/{cd_mun_ibge}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumo do município
         * @description Desempenho de cada grupo no município, por cargo.
         */
        get: operations["municipio_api_municipios__cd_mun_ibge__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Abrangencia
         * @description Região em que o candidato disputa: o front enquadra o mapa por ela.
         */
        Abrangencia: {
            /**
             * Tipo
             * @description `pais` (presidente) ou `uf`.
             * @enum {string}
             */
            tipo: "pais" | "uf";
            /**
             * Uf
             * @description Sigla da UF; null quando `tipo = pais`.
             */
            uf: string | null;
        };
        /**
         * Ano
         * @description Anos de eleição geral suportados.
         * @enum {integer}
         */
        Ano: 2022 | 2026;
        /**
         * CandidatoResumo
         * @description Candidato com votos e taxas na sua circunscrição (cargo × UF).
         */
        CandidatoResumo: {
            /** Ano */
            ano: number;
            /** Sq Candidato */
            sq_candidato: number;
            /** Nm Urna */
            nm_urna: string;
            /** Sg Uf */
            sg_uf: string;
            /** Cargo */
            cargo: string;
            partido: components["schemas"]["Partido"];
            /**
             * Situacao
             * @description `ds_situacao_candidatura` (APTO, INDEFERIDO…); null = TSE ainda não publicou.
             */
            situacao: string | null;
            /**
             * Resultado
             * @description `ds_sit_tot_turno` (ELEITO, SUPLENTE…); null se sem apuração.
             */
            resultado: string | null;
            /**
             * Votos
             * @description Votos nominais válidos (spec §2.1).
             */
            votos: number;
            /**
             * Pct Validos
             * @description % dos válidos do cargo na UF (§2.2).
             */
            pct_validos: number | null;
            /**
             * Penetracao
             * @description ‰ dos aptos do cargo na UF (§2.3).
             */
            penetracao: number | null;
            /**
             * Indicado
             * @description Candidatura indicada pelo grupo (`origem=indicado` na lista de referência); false para candidatos próprios ou fora da lista.
             */
            indicado: boolean;
            abrangencia: components["schemas"]["Abrangencia"];
        };
        /**
         * CandidaturaBusca
         * @description Candidatura achada: o bastante para listar, escolher e enquadrar o mapa.
         */
        CandidaturaBusca: {
            /** Ano */
            ano: number;
            /** Sq Candidato */
            sq_candidato: number;
            /** Nm Urna */
            nm_urna: string;
            /**
             * Nome
             * @description Nome civil, como no registro de candidatura do TSE.
             */
            nome: string | null;
            /**
             * Numero
             * @description Número de urna.
             */
            numero: number | null;
            /** Cargo */
            cargo: string;
            /**
             * Uf
             * @description UF da candidatura; `BR` para presidente.
             */
            uf: string;
            partido: components["schemas"]["Partido"];
            /**
             * Votos
             * @description Votos nominais válidos (spec §2.1); 0 sem apuração.
             */
            votos: number;
            /**
             * Resultado
             * @description `ds_sit_tot_turno`; null se sem apuração.
             */
            resultado: string | null;
            /**
             * Indicado
             * @description Candidatura indicada pelo grupo (lista de referência).
             */
            indicado: boolean;
            /**
             * Pessoa Id Publico
             * @description Hash curto e não reversível da pessoa, só para ligar anos. Não é o `pessoa_id` interno nem identifica ninguém fora desta API.
             */
            pessoa_id_publico: string;
            abrangencia: components["schemas"]["Abrangencia"];
        };
        /**
         * Cargo
         * @description `ds_cargo` em maiúsculas; o ETL grava em caixa de título e as views aplicam `upper`.
         * @enum {string}
         */
        Cargo: "PRESIDENTE" | "GOVERNADOR" | "SENADOR" | "DEPUTADO FEDERAL" | "DEPUTADO ESTADUAL" | "DEPUTADO DISTRITAL";
        /**
         * ComparacaoResumo
         * @description Comparação configurada entre dois grupos.
         */
        ComparacaoResumo: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** De */
            de: string;
            /** Para */
            para: string;
        };
        /**
         * Comparativo
         * @description Corpo de GET /comparativo.
         * @example {
         *       "cargo": "DEPUTADO FEDERAL",
         *       "comparacao": "evolucao_mbl",
         *       "de": {
         *         "ano": 2022,
         *         "id": "mbl_2022",
         *         "rotulo": "MBL 2022"
         *       },
         *       "dt_geracao": "2026-10-06",
         *       "kpis": {
         *         "delta_penetracao": 37.1,
         *         "ganho_absoluto": 720,
         *         "penetracao_de": 70.3,
         *         "penetracao_para": 107.4,
         *         "retencao": 1.62,
         *         "swing_pp": 5.9,
         *         "votos_de": 1160,
         *         "votos_para": 1880
         *       },
         *       "mesmos_candidatos": false,
         *       "municipios": [],
         *       "n_de": 3,
         *       "n_para": 3,
         *       "para": {
         *         "ano": 2026,
         *         "id": "mbl_2026",
         *         "rotulo": "MBL 2026"
         *       },
         *       "rotulo": "MBL 2022 → MBL 2026",
         *       "uf": "SP"
         *     }
         */
        Comparativo: {
            /** Comparacao */
            comparacao: string;
            /** Rotulo */
            rotulo: string;
            de: components["schemas"]["GrupoRef"];
            para: components["schemas"]["GrupoRef"];
            /** Cargo */
            cargo: string;
            /** Uf */
            uf: string | null;
            /** Mesmos Candidatos */
            mesmos_candidatos: boolean;
            /**
             * N De
             * @description Candidaturas aptas do lado 'de'; null = situação não publicada.
             */
            n_de: number | null;
            /** N Para */
            n_para: number | null;
            kpis: components["schemas"]["KpisComparativo"];
            /** @description Quebras comuns 2022+2026 da penetração municipal (as dos dois mapas). */
            escala_sugerida: components["schemas"]["EscalaSugerida"];
            /** Municipios */
            municipios: components["schemas"]["EvolucaoMunicipio"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * Detalhe
         * @description Numerador e denominadores de um território.
         */
        Detalhe: {
            /** Votos */
            votos: number;
            /** Aptos */
            aptos: number;
            /**
             * Validos
             * @description null no H3: não há 'válidos' por célula (§2.2).
             */
            validos: number | null;
            /**
             * Taxa
             * @description Valor do indicador; null = sem dado (denominador 0).
             */
            taxa: number | null;
            /**
             * Nome
             * @description Nome do município (também nas chaves `IBGE-zona`); null no H3 ou se o município não consta do cadastro.
             */
            nome?: string | null;
        };
        /**
         * EscalaSugerida
         * @description Sugestão de classes para a legenda (spec §8.2); o front decide a cor final.
         */
        EscalaSugerida: {
            /**
             * Tipo
             * @description `sequencial` (taxas) ou `simbolo_proporcional` (absolutos).
             */
            tipo: string;
            /** Paleta */
            paleta: string;
            /**
             * Quebras
             * @description Cortes internos da legenda; null quando não há como calcular (ver `aviso`).
             */
            quebras: number[] | null;
            /**
             * Aviso
             * @description Por que `quebras` é null, se for.
             */
            aviso?: string | null;
            /**
             * Anos
             * @description Anos cujos valores entraram nas quebras (2022+2026 numa comparação).
             */
            anos?: number[];
        };
        /**
         * EvolucaoMunicipio
         * @description Evolução numa AMC (município IBGE com desmembramentos agregados, §5.1).
         */
        EvolucaoMunicipio: {
            /** Cd Amc */
            cd_amc: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
            /** Penetracao De */
            penetracao_de: number | null;
            /** Penetracao Para */
            penetracao_para: number | null;
            /**
             * Delta Penetracao
             * @description ‰ — métrica-âncora.
             */
            delta_penetracao: number | null;
            /**
             * Swing Pp
             * @description p.p. de votos válidos.
             */
            swing_pp: number | null;
            /**
             * Retencao
             * @description votos_para / votos_de; null se votos_de = 0.
             */
            retencao: number | null;
            /**
             * Ganho Absoluto
             * @description null se a AMC só existe num dos anos.
             */
            ganho_absoluto: number | null;
            /** Votos De */
            votos_de: number | null;
            /** Votos Para */
            votos_para: number | null;
        };
        /**
         * FichaCandidato
         * @description Ficha completa: votação, geografia e finanças.
         */
        FichaCandidato: {
            candidato: components["schemas"]["CandidatoResumo"];
            /** Votos Total */
            votos_total: number;
            /** Votos Por Uf */
            votos_por_uf: components["schemas"]["VotosUF"][];
            /**
             * Votos Por Municipio
             * @description Top N por votos.
             */
            votos_por_municipio: components["schemas"]["VotosMunicipio"][];
            /** @description null se não há prestação de contas. */
            gastos: components["schemas"]["ResumoCustoCandidato"] | null;
            receitas: components["schemas"]["ResumoReceitasOut"] | null;
            /**
             * Contas Parciais
             * @description Prestação de contas ainda parcial (2026).
             */
            contas_parciais: boolean;
            /**
             * Base Ipca
             * @description Mês-base da correção do IPCA (valores de 2022).
             */
            base_ipca: string | null;
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * GastoCandidato
         * @description Contas de um candidato do grupo.
         */
        GastoCandidato: {
            /** Sq Candidato */
            sq_candidato: number;
            /** Nm Urna */
            nm_urna: string;
            /** Sg Uf */
            sg_uf: string;
            /** Cargo */
            cargo: string;
            /** Receita Total */
            receita_total: number;
            custo: components["schemas"]["ResumoCustoCandidato"];
        };
        /**
         * Gastos
         * @description Corpo de GET /gastos.
         * @example {
         *       "agregado": {
         *         "candidatos_sem_voto_excluidos": 0,
         *         "custo_voto_contratado": 88.98,
         *         "custo_voto_pago": 72.03,
         *         "despesa_contratada": 105000,
         *         "despesa_paga": 85000,
         *         "divida": 20000,
         *         "mediana_custo_voto_contratado": 63.89,
         *         "votos": 1180
         *       },
         *       "ano": 2026,
         *       "cargo": "DEPUTADO FEDERAL",
         *       "contas_parciais": true,
         *       "dt_geracao": "2026-10-06",
         *       "grupo": "missao_2026",
         *       "por_candidato": [],
         *       "receitas": {
         *         "pct_autofinanciamento": 8.47,
         *         "pct_publico": 67.8,
         *         "por_categoria": {
         *           "fefc": 70000,
         *           "fundo_partidario": 10000
         *         },
         *         "receita_financeira": 116000,
         *         "receita_total": 118000
         *       },
         *       "uf": "SP"
         *     }
         */
        Gastos: {
            /** Grupo */
            grupo: string;
            /** Ano */
            ano: number;
            /** Cargo */
            cargo: string | null;
            /** Uf */
            uf: string | null;
            agregado: components["schemas"]["ResumoCustoGrupo"];
            receitas: components["schemas"]["ResumoReceitasOut"];
            /** Por Candidato */
            por_candidato: components["schemas"]["GastoCandidato"][];
            /** Contas Parciais */
            contas_parciais: boolean;
            /** Base Ipca */
            base_ipca: string | null;
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * Grupo
         * @description Grupo comparável definido em config/grupos.yaml.
         */
        Grupo: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** Ano */
            ano: number;
        };
        /**
         * GrupoRef
         * @description Grupo de um dos lados da comparação.
         */
        GrupoRef: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** Ano */
            ano: number;
        };
        /**
         * GrupoResumo
         * @description Item de GET /grupos.
         */
        GrupoResumo: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** Ano */
            ano: number;
            /**
             * N Candidaturas
             * @description Candidaturas do grupo presentes nos dados.
             */
            n_candidaturas: number;
        };
        /**
         * GruposResposta
         * @description Corpo de GET /grupos.
         * @example {
         *       "comparacoes": [
         *         {
         *           "de": "mbl_2022",
         *           "id": "evolucao_mbl",
         *           "para": "mbl_2026",
         *           "rotulo": "MBL 2022 → MBL 2026"
         *         }
         *       ],
         *       "grupos": [
         *         {
         *           "ano": 2026,
         *           "id": "missao_2026",
         *           "n_candidaturas": 3,
         *           "rotulo": "Partido Missão 2026"
         *         }
         *       ]
         *     }
         */
        GruposResposta: {
            /** Grupos */
            grupos: components["schemas"]["GrupoResumo"][];
            /** Comparacoes */
            comparacoes: components["schemas"]["ComparacaoResumo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Indicador
         * @description Indicadores mapeáveis (spec §2): taxas em coroplético, absoluto em símbolo.
         * @enum {string}
         */
        Indicador: "penetracao" | "pct_validos" | "votos";
        /**
         * KpisComparativo
         * @description Os mesmos indicadores sobre o recorte inteiro (Σ votos / Σ base, não média de AMCs).
         */
        KpisComparativo: {
            /** Penetracao De */
            penetracao_de: number | null;
            /** Penetracao Para */
            penetracao_para: number | null;
            /** Delta Penetracao */
            delta_penetracao: number | null;
            /** Swing Pp */
            swing_pp: number | null;
            /** Retencao */
            retencao: number | null;
            /** Ganho Absoluto */
            ganho_absoluto: number | null;
            /** Votos De */
            votos_de: number | null;
            /** Votos Para */
            votos_para: number | null;
        };
        /**
         * KpisGrupo
         * @description Grupo como candidato coletivo no recorte (cargo × UF): soma única, nunca de cargos.
         */
        KpisGrupo: {
            /**
             * Votos
             * @description Σ votos nominais válidos dos membros (spec §2.1).
             */
            votos: number;
            /**
             * Aptos
             * @description Aptos do cargo no recorte (denominador da penetração).
             */
            aptos: number;
            /**
             * Validos
             * @description Votos válidos do cargo no recorte (denominador do %).
             */
            validos: number;
            /**
             * Pct Validos
             * @description % dos válidos do cargo (§2.2).
             */
            pct_validos: number | null;
            /**
             * Penetracao
             * @description ‰ dos aptos do cargo (§2.3).
             */
            penetracao: number | null;
        };
        /**
         * ListaCandidatos
         * @description Página de candidatos.
         * @example {
         *       "itens": [
         *         {
         *           "abrangencia": {
         *             "tipo": "uf",
         *             "uf": "SP"
         *           },
         *           "ano": 2026,
         *           "cargo": "DEPUTADO FEDERAL",
         *           "indicado": false,
         *           "nm_urna": "A",
         *           "partido": {
         *             "numero": 14,
         *             "sigla": "MISSÃO"
         *           },
         *           "pct_validos": 8.06,
         *           "penetracao": 57.14,
         *           "resultado": "SUPLENTE",
         *           "sg_uf": "SP",
         *           "situacao": "APTO",
         *           "sq_candidato": 3,
         *           "votos": 1000
         *         }
         *       ],
         *       "kpis": {
         *         "aptos": 17500,
         *         "pct_validos": 8.06,
         *         "penetracao": 57.14,
         *         "validos": 12400,
         *         "votos": 1000
         *       },
         *       "limite": 200,
         *       "offset": 0,
         *       "total": 1
         *     }
         */
        ListaCandidatos: {
            /** Total */
            total: number;
            /** Limite */
            limite: number;
            /** Offset */
            offset: number;
            /** Itens */
            itens: components["schemas"]["CandidatoResumo"][];
            /** @description Indicadores do grupo inteiro no recorte; null sem `cargo` (não se somam cargos) ou sem candidaturas. */
            kpis: components["schemas"]["KpisGrupo"] | null;
        };
        /**
         * ListaPessoas
         * @description Corpo de GET /evolucao/pessoas.
         */
        ListaPessoas: {
            /** Total */
            total: number;
            /** Limite */
            limite: number;
            /** Itens */
            itens: components["schemas"]["PessoaEvolucao"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * Mapa
         * @description Corpo de GET /mapa. Chaves: IBGE (município), `IBGE-zona`, ou índice H3.
         * @example {
         *       "ano": 2026,
         *       "denominador": "aptos",
         *       "detalhes": {
         *         "3550308": {
         *           "aptos": 15000,
         *           "taxa": 73.33,
         *           "validos": 10500,
         *           "votos": 1100
         *         }
         *       },
         *       "dt_geracao": "2026-10-06",
         *       "escala_sugerida": {
         *         "paleta": "viridis",
         *         "quebras": [
         *           20,
         *           40,
         *           60,
         *           70
         *         ],
         *         "tipo": "sequencial"
         *       },
         *       "indicador": "penetracao",
         *       "n_candidaturas": 2,
         *       "nivel": "municipio",
         *       "unidade": "‰",
         *       "valores": {
         *         "3509502": 20,
         *         "3550308": 73.33
         *       }
         *     }
         */
        Mapa: {
            /** Ano */
            ano: number;
            /** Nivel */
            nivel: string;
            /** Indicador */
            indicador: string;
            /** Valores */
            valores: {
                [key: string]: number | null;
            };
            /** Detalhes */
            detalhes: {
                [key: string]: components["schemas"]["Detalhe"];
            };
            escala_sugerida: components["schemas"]["EscalaSugerida"];
            /** Unidade */
            unidade: string;
            /** Denominador */
            denominador: string | null;
            /** N Candidaturas */
            n_candidaturas: number;
            /**
             * Votos Sem Coordenada
             * @description Só no H3: votos do recorte em locais sem coordenada, que não aparecem em nenhuma célula. null nos demais níveis.
             */
            votos_sem_coordenada?: number | null;
            /**
             * Pct Votos Sem Coordenada
             * @description `votos_sem_coordenada` em % dos votos do recorte (o front avisa se > 5%).
             */
            pct_votos_sem_coordenada?: number | null;
            /**
             * Votos Fora Do Mapa
             * @description Votos do recorte sem município IBGE (exterior, `ZZ`): contam no total do candidato, mas não têm polígono e ficam fora de `valores`.
             * @default 0
             */
            votos_fora_do_mapa: number;
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * Meta
         * @description Dimensões disponíveis para filtros.
         */
        Meta: {
            /** Anos */
            anos: number[];
            /** Ufs */
            ufs: string[];
            /** Cargos */
            cargos: string[];
            /** Grupos */
            grupos: components["schemas"]["Grupo"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * Nivel
         * @description Recorte espacial do mapa.
         * @enum {string}
         */
        Nivel: "municipio" | "zona" | "h3";
        /**
         * Partido
         * @description Partido da candidatura.
         */
        Partido: {
            /** Numero */
            numero: number;
            /** Sigla */
            sigla: string;
        };
        /**
         * PessoaEvolucao
         * @description Uma pessoa com candidatura em 2022 e em 2026, resumida nos dois anos.
         */
        PessoaEvolucao: {
            /** Pessoa Id Publico */
            pessoa_id_publico: string;
            /**
             * Nome
             * @description Nome de urna em 2026.
             */
            nome: string;
            /**
             * Mesmo Cargo
             * @description Concorreu ao mesmo cargo nos dois anos.
             */
            mesmo_cargo: boolean;
            /**
             * Comparavel
             * @description Entra em /comparativo: mesmo cargo e não Senado (1 voto × 2 votos, §1.8).
             */
            comparavel: boolean;
            /** @description Candidatura de 2022. */
            de: components["schemas"]["CandidaturaBusca"];
            /** @description Candidatura de 2026. */
            para: components["schemas"]["CandidaturaBusca"];
        };
        /**
         * Ponto
         * @description Local de votação.
         */
        Ponto: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Votos */
            votos: number;
        };
        /**
         * Pontos
         * @description Corpo de GET /mapa/pontos (densidade de votos por local).
         */
        Pontos: {
            /** Ano */
            ano: number;
            /**
             * Total
             * @description Pontos no recorte (locais com voto ou, na grade, células).
             */
            total: number;
            /**
             * Grade Graus
             * @description Sem `uf` (Brasil): tamanho em graus da célula lat/lon em que os locais são somados (cada ponto é o centroide ponderado por votos). null = um ponto por local.
             */
            grade_graus: number | null;
            /** Limite */
            limite: number;
            /** Offset */
            offset: number;
            /**
             * Truncado
             * @description Há mais páginas além desta.
             */
            truncado: boolean;
            /**
             * Votos Sem Coordenada
             * @description Votos do recorte (UF inteira, não só a página) em locais sem coordenada, que não viram ponto.
             */
            votos_sem_coordenada: number;
            /**
             * Pct Votos Sem Coordenada
             * @description `votos_sem_coordenada` em % dos votos do recorte (o front avisa se > 5%).
             */
            pct_votos_sem_coordenada: number;
            /** Pontos */
            pontos: components["schemas"]["Ponto"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * ResultadoBusca
         * @description Corpo de GET /busca.
         * @example {
         *       "dt_geracao": "2026-10-06",
         *       "itens": [
         *         {
         *           "abrangencia": {
         *             "tipo": "uf",
         *             "uf": "SP"
         *           },
         *           "ano": 2026,
         *           "cargo": "DEPUTADO FEDERAL",
         *           "indicado": false,
         *           "nm_urna": "A",
         *           "nome": "ANA ALVES DA SILVA",
         *           "numero": 1415,
         *           "partido": {
         *             "numero": 14,
         *             "sigla": "MISSÃO"
         *           },
         *           "pessoa_id_publico": "3f2a9c1d7b40",
         *           "resultado": "SUPLENTE",
         *           "sq_candidato": 3,
         *           "uf": "SP",
         *           "votos": 1000
         *         }
         *       ],
         *       "limite": 20,
         *       "total": 1
         *     }
         */
        ResultadoBusca: {
            /**
             * Total
             * @description Candidaturas que casam (além da página devolvida).
             */
            total: number;
            /** Limite */
            limite: number;
            /** Itens */
            itens: components["schemas"]["CandidaturaBusca"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * ResumoCargo
         * @description Desempenho do grupo num cargo dentro do município (um cargo por vez, spec §0).
         */
        ResumoCargo: {
            /** Cargo */
            cargo: string;
            /** N Candidaturas */
            n_candidaturas: number;
            /** Votos */
            votos: number;
            /** Aptos */
            aptos: number;
            /** Penetracao */
            penetracao: number | null;
            /** Pct Validos */
            pct_validos: number | null;
            /** Votos Por Km2 */
            votos_por_km2: number | null;
        };
        /**
         * ResumoCustoCandidato
         * @description Despesa (sem transferências) e custo por voto de um candidato.
         */
        ResumoCustoCandidato: {
            /**
             * Despesa Contratada
             * @description R$ da própria campanha, sem repasses.
             */
            despesa_contratada: number;
            /**
             * Despesa Paga
             * @description R$ pagos da própria campanha, sem repasses.
             */
            despesa_paga: number;
            /**
             * Divida
             * @description contratada − paga (§4.2).
             */
            divida: number;
            /** Votos */
            votos: number;
            /**
             * Custo Voto Contratado
             * @description R$/voto = despesa contratada ÷ votos nominais. Exclui repasses a outros candidatos/partidos (§4.2). null se votos = 0.
             */
            custo_voto_contratado: number | null;
            /**
             * Custo Voto Pago
             * @description R$/voto pago; exclui repasses a outros candidatos/partidos (§4.2).
             */
            custo_voto_pago: number | null;
        };
        /**
         * ResumoCustoGrupo
         * @description Agregado: Σ despesa / Σ votos, não média de razões (§4.2).
         */
        ResumoCustoGrupo: {
            /**
             * Despesa Contratada
             * @description Σ da própria campanha, sem repasses.
             */
            despesa_contratada: number;
            /**
             * Despesa Paga
             * @description Σ paga da própria campanha, sem repasses.
             */
            despesa_paga: number;
            /** Divida */
            divida: number;
            /** Votos */
            votos: number;
            /**
             * Custo Voto Contratado
             * @description Σ despesa contratada ÷ Σ votos; exclui repasses a outros candidatos/partidos (§4.2).
             */
            custo_voto_contratado: number | null;
            /**
             * Custo Voto Pago
             * @description Σ despesa paga ÷ Σ votos; exclui repasses a outros candidatos/partidos.
             */
            custo_voto_pago: number | null;
            /**
             * Mediana Custo Voto Contratado
             * @description Mediana entre candidatos com voto; exclui repasses (§4.2).
             */
            mediana_custo_voto_contratado: number | null;
            /** Candidatos Sem Voto Excluidos */
            candidatos_sem_voto_excluidos: number;
        };
        /**
         * ResumoGrupo
         * @description Grupo e seus cargos no município.
         */
        ResumoGrupo: {
            /** Id */
            id: string;
            /** Rotulo */
            rotulo: string;
            /** Ano */
            ano: number;
            /** Cargos */
            cargos: components["schemas"]["ResumoCargo"][];
        };
        /**
         * ResumoMunicipio
         * @description Corpo de GET /municipios/{cd_mun_ibge}.
         * @example {
         *       "area_km2": 1521.11,
         *       "cd_mun_ibge": 3550308,
         *       "dt_geracao": "2026-10-06",
         *       "grupos": [
         *         {
         *           "ano": 2026,
         *           "cargos": [
         *             {
         *               "aptos": 15000,
         *               "cargo": "DEPUTADO FEDERAL",
         *               "n_candidaturas": 2,
         *               "pct_validos": 10.48,
         *               "penetracao": 73.33,
         *               "votos": 1100,
         *               "votos_por_km2": 0.72
         *             }
         *           ],
         *           "id": "missao_2026",
         *           "rotulo": "Partido Missão 2026"
         *         }
         *       ],
         *       "nome": "São Paulo",
         *       "uf": "SP"
         *     }
         */
        ResumoMunicipio: {
            /** Cd Mun Ibge */
            cd_mun_ibge: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
            /** Area Km2 */
            area_km2: number | null;
            /** Grupos */
            grupos: components["schemas"]["ResumoGrupo"][];
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * ResumoReceitasOut
         * @description Receita por categoria (§4.1) e dependência de recursos públicos.
         */
        ResumoReceitasOut: {
            /** Por Categoria */
            por_categoria: {
                [key: string]: number;
            };
            /** Receita Total */
            receita_total: number;
            /** Receita Financeira */
            receita_financeira: number;
            /**
             * Pct Publico
             * @description FEFC + Fundo Partidário, % da receita total.
             */
            pct_publico: number | null;
            /** Pct Autofinanciamento */
            pct_autofinanciamento: number | null;
        };
        /**
         * Saude
         * @description Estado da API e dos dados.
         */
        Saude: {
            /** Status */
            status: string;
            /** Versao */
            versao: string;
            /** Dt Geracao */
            dt_geracao: string;
        };
        /**
         * UF
         * @description Unidades da federação (sem exterior: `ZZ` não tem mapa).
         * @enum {string}
         */
        UF: "AC" | "AL" | "AM" | "AP" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MG" | "MS" | "MT" | "PA" | "PB" | "PE" | "PI" | "PR" | "RJ" | "RN" | "RO" | "RR" | "RS" | "SC" | "SE" | "SP" | "TO";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VotosMunicipio
         * @description Votos do candidato num município.
         */
        VotosMunicipio: {
            /** Cd Mun Ibge */
            cd_mun_ibge: number;
            /** Nome */
            nome: string;
            /** Uf */
            uf: string;
            /** Votos */
            votos: number;
            /**
             * Penetracao
             * @description ‰ dos aptos do município no cargo.
             */
            penetracao: number | null;
        };
        /**
         * VotosUF
         * @description Votos do candidato numa UF.
         */
        VotosUF: {
            /** Uf */
            uf: string;
            /** Votos */
            votos: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Saude"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    grupos_api_grupos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GruposResposta"];
                };
            };
        };
    };
    candidatos_api_candidatos_get: {
        parameters: {
            query: {
                /** @description Id do grupo em config/grupos.yaml (ex.: missao_2026). */
                grupo: string;
                uf?: components["schemas"]["UF"] | null;
                cargo?: components["schemas"]["Cargo"] | null;
                limite?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaCandidatos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ficha_api_candidatos__ano___sq_candidato__get: {
        parameters: {
            query?: {
                /** @description Municípios no ranking. */
                top?: number;
            };
            header?: never;
            path: {
                ano: components["schemas"]["Ano"];
                sq_candidato: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaCandidato"];
                };
            };
            /** @description Candidato inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mapa_api_mapa_get: {
        parameters: {
            query: {
                ano: components["schemas"]["Ano"];
                cargo: components["schemas"]["Cargo"];
                uf?: components["schemas"]["UF"] | null;
                nivel?: components["schemas"]["Nivel"];
                /** @description Id do grupo; exclusivo com sq_candidato. */
                grupo?: string | null;
                /** @description SQ_CANDIDATO; exclusivo com grupo. */
                sq_candidato?: number | null;
                indicador?: components["schemas"]["Indicador"];
                /** @description Id em `comparacoes`: a escala usa quebras comuns aos dois anos (exige `grupo` = um dos lados). */
                comparacao?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapa"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pontos_api_mapa_pontos_get: {
        parameters: {
            query: {
                ano: components["schemas"]["Ano"];
                cargo: components["schemas"]["Cargo"];
                /** @description Sem UF (Brasil, ex.: presidente): locais somados em células de 0,1°. */
                uf?: components["schemas"]["UF"] | null;
                /** @description Id do grupo; exclusivo com sq_candidato. */
                grupo?: string | null;
                /** @description SQ_CANDIDATO; exclusivo com grupo. */
                sq_candidato?: number | null;
                limite?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pontos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gastos_api_gastos_get: {
        parameters: {
            query: {
                /** @description Id do grupo em config/grupos.yaml (ex.: missao_2026). */
                grupo: string;
                uf?: components["schemas"]["UF"] | null;
                cargo?: components["schemas"]["Cargo"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gastos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparativo_api_comparativo_get: {
        parameters: {
            query: {
                cargo: components["schemas"]["Cargo"];
                /** @description Id em `comparacoes` (ex.: evolucao_mbl). */
                comparacao?: string | null;
                uf?: components["schemas"]["UF"] | null;
                /** @description Só pessoas que concorreram nos dois anos (pessoa_id). */
                mesmos_candidatos?: boolean;
                /** @description Seleção do usuário: `pessoa_id_publico` (de /busca ou /evolucao/pessoas); compara as candidaturas delas em 2022 e 2026. Exclusivo com `comparacao`. */
                pessoas?: string[] | null;
                /** @description Seleção: `sq_candidato` de 2022. */
                sq_2022?: number[] | null;
                /** @description Seleção: `sq_candidato` de 2026. */
                sq_2026?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparativo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    busca_api_busca_get: {
        parameters: {
            query: {
                /** @description Nome de urna ou civil (sem acento, qualquer caixa; início de palavra antes de trecho), número de urna (prefixo), número ou sigla do partido. */
                q: string;
                ano?: components["schemas"]["Ano"] | null;
                cargo?: components["schemas"]["Cargo"] | null;
                uf?: components["schemas"]["UF"] | null;
                /** @description Id do grupo; exclusivo com sq_candidato. */
                grupo?: string | null;
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoBusca"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evolucao_pessoas_api_evolucao_pessoas_get: {
        parameters: {
            query?: {
                /** @description Nome (urna ou civil), como em /busca. */
                q?: string | null;
                uf?: components["schemas"]["UF"] | null;
                /** @description Exige este cargo nos dois anos. */
                cargo?: components["schemas"]["Cargo"] | null;
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaPessoas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    municipio_api_municipios__cd_mun_ibge__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Código IBGE de 7 dígitos. */
                cd_mun_ibge: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoMunicipio"];
                };
            };
            /** @description Município inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
